on:
    schedule:
    -cron: "0 0 * ? * * *"
    push: balls.py

import requests #dependency

url = "https://discord.com/api/webhooks/1204016690657103883/ssTV_-jAdNRfjmBJPyV-9sEoPoZkWW2AkkDkDohWG1hf2yfAlj4GcVt_TB3DinQSDNu4" #webhook url, from here: https://i.imgur.com/f9XnAew.png

#for all params, see https://discordapp.com/developers/docs/resources/webhook#execute-webhook
data = {
    "content" : "message content",
    "username" : "custom username"
}

#leave this out if you dont want an embed
#for all params, see https://discordapp.com/developers/docs/resources/channel#embed-object
data["embeds"] = [
    {
        "description" : "text in embed",
        "title" : "embed title"
    }
]

result = requests.post(url, json = data)

try:
    result.raise_for_status()
except requests.exceptions.HTTPError as err:
    print(err)
else:
    print("Payload delivered successfully, code {}.".format(result.status_code))
